WITH AvailableCars AS (
    SELECT
        C.CAR_ID,
        C.CAR_TYPE,
        C.DAILY_FEE,
        COALESCE(DP.DISCOUNT_RATE, 0) AS DISCOUNT_RATE
    FROM
        CAR_RENTAL_COMPANY_CAR C
    LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN DP
        ON C.CAR_TYPE = DP.CAR_TYPE AND DP.DURATION_TYPE = '30일 이상'
    WHERE
        C.CAR_TYPE IN ('세단', 'SUV')
        AND NOT EXISTS (
            SELECT 1
            FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY RH
            WHERE C.CAR_ID = RH.CAR_ID
                AND RH.START_DATE <= '2022-11-30'
                AND RH.END_DATE >= '2022-11-01'
        )
)
SELECT
    CAR_ID,
    CAR_TYPE,
    FLOOR(DAILY_FEE * 30 * (1 - DISCOUNT_RATE / 100.0)) AS FEE
FROM
    AvailableCars
WHERE
    FLOOR(DAILY_FEE * 30 * (1 - DISCOUNT_RATE / 100.0)) BETWEEN 500000 AND 1999999
ORDER BY
    FEE DESC,
    CAR_TYPE ASC,
    CAR_ID DESC;